---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: openebs-self-install-
  namespace: litmus
spec:
  template:
    metadata:
      name: litmus
      labels:
        app: openebs-self-install-check-litmus
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      volumes:
      - name: secret-volume
        secret:
          secretName: director-user-pass
      containers:
      - name: ansibletest
        image: mayadataio/dop-validator:ci 
        imagePullPolicy: Always
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
        env:

          ## Takes director-ip from configmap director-ip
          - name: DIRECTOR_IP
            valueFrom:
              configMapKeyRef:
                name: director-ip
                key: ip

          ## Takes group-id from configmap group-id
          - name: GROUP_ID
            valueFrom:
              configMapKeyRef:
                name: group-id
                key: id

          ## Give director userid in secret
          - name: DIRECTOR_USERID
            valueFrom:
              secretKeyRef:
                name: director-user-pass
                key: username
                
          ## Give director password in secret
          - name: DIRECTOR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: director-user-pass
                key: password

          - name: ANSIBLE_STDOUT_CALLBACK
            value: default  

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./litmus/director/openebs-self-install/test.yml -i /etc/ansible/hosts -v; exit 0"]
        
